name: libhut CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: devenv
        run: |
          sudo apt update -yq
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt install -yq build-essential software-properties-common cmake gcc-11 g++-11
          sudo update-alternatives --remove-all cpp
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11  --slave /usr/bin/cpp cpp /usr/bin/cpp-11
      - name: dependencies
        run: |
          sudo apt install -yq wayland-protocols glslang-tools vulkan-utils libwayland-bin weston libvulkan-dev libglm-dev libwayland-dev libxkbcommon-dev libgtest-dev libharfbuzz-dev
      - name: dumpenv
        run: |
          export
          lsb_release -a
          bash --version
          cmake --version
          make --version
          gcc --version
          g++ --version
          wayland-scanner --version
          glslangValidator --version
          weston --version
          vulkaninfo
      - name: cmake
        run: cmake .
      - name: build
        run: cmake --build . --parallel
      - name: ctest
        run: |
          mkdir xdg_runtime_dir
          export XDG_RUNTIME_DIR=xdg_runtime_dir
          export HUT_DISPLAY=headless
          sudo usermod -a -G weston-launch ${USER}
          weston --backend=headless-backend.so --socket=headless &
          sleep 5
          ctest --verbose .
