name: libhut CI

on:
  workflow_dispatch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: update
        run: |
          apt update -yq
      - name: devenv
        run: |
          apt install -yq build-essential software-properties-common cmake clang-format clang-tidy clang libc++-dev
      - name: builddeps
        run: |
          apt install -yq wayland-protocols glslang-tools libvulkan-dev libglm-dev libwayland-bin libwayland-dev libxkbcommon-dev libgtest-dev libharfbuzz-dev librenderdoc-dev
      - name: dumpenv
        run: |
          export
          lsb_release -a
          bash --version
          cmake --version
          make --version
          clang --version
          clang++ --version
          wayland-scanner --version
          glslangValidator --version
      - name: cmake
        run: |
          CC=clang
          CXX=clang++
          CXXFLAGS=-stdlib=libc++
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON -DHUT_CI=True .
      - name: build
        run: |
          cmake --build . --parallel
      - name: tidy
        run: |
          shopt -s globstar
          clang-tidy --version
          clang-tidy -p . ext/**/*.cpp src/**/*.cpp tst/**/*.cpp
      - name: format
        run: |
          shopt -s globstar
          clang-format --version
          clang-format --style=file --dry-run ext/**/*.hpp ext/**/*.cpp inc/**/*.hpp src/**/*.cpp tst/**/*.hpp tst/**/*.cpp
      - name: testdeps
        run: |
          apt install -yq vulkan-tools vulkan-validationlayers weston valgrind 
          weston --version
          vulkaninfo
      - name: ctest
        run: |
          mkdir xdg_runtime_dir
          chmod 0700 xdg_runtime_dir
          export XDG_RUNTIME_DIR=xdg_runtime_dir
          export HUT_DISPLAY=headless
          weston --backend=headless-backend.so --socket=headless &
          sleep 10
          valgrind ./hut_unittests
