name: libhut CI

on:
  workflow_dispatch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update
        run: |
          sudo apt update -yq
      - name: devenv
        run: |
          sudo apt install -yq build-essential software-properties-common cmake clang llvm
          shopt -s globstar
      - name: builddeps
        run: |
          sudo apt install -yq wayland-protocols glslang-tools libvulkan-dev libglm-dev libwayland-bin libwayland-dev libxkbcommon-dev libgtest-dev libharfbuzz-dev
      - name: dumpenv
        run: |
          export
          lsb_release -a
          bash --version
          shopt
          cmake --version
          make --version
          cc --version
          cxx --version
          wayland-scanner --version
          glslangValidator --version
      - name: cmake
        run: cmake .
      - name: build
        run: cmake --build . --parallel
      - name: tidy
        run: clang-tidy ext/**/*.cpp src/**/*.cpp tst/**/*.cpp
      - name: format
        run: clang-format --style=file --Werror --dry-run ext/**/*.hpp ext/**/*.cpp inc/**/*.hpp src/**/*.hpp src/**/*.cpp tst/**/*.hpp tst/**/*.cpp
      - name: testdeps
        run: |
          sudo apt install -yq vulkan-utils weston
          weston --version
          vulkaninfo
      - name: ctest
        run: |
          mkdir xdg_runtime_dir
          export XDG_RUNTIME_DIR=xdg_runtie_dir
          export HUT_DISPLAY=headless
          sudo usermod -a -G weston-launch ${USER}
          weston --backend=headless-backend.so --socket=headless &
          sleep 5
          ctest --verbose .
